### ISSUE TITLE
OR operand in brackets doesn't function properly

### ISSUE THREAD

**Issue by jamal-badawi-99** [m-onyshchuk/stugna#2]
I have the following rule:
` {
    condition:
      "(factOne = 1 OR factTwo = 1) AND factThree = 1 AND (factFour = 1 OR factFive = 1) AND factSix = 1 AND (factSeven = 1 OR factEight = 1)",
    factValue: "match",
    factName: "rule",
  }`

The issue is that it the rule won't fire unless i match all facts from one to eight even though the factsAllAsMap() returns:
`[
factOne: 1,
factThree: 1,
factFive: 1,
factSix: 1,
factSeven: 1,
]`

**Comment by m-onyshchuk** [comment]
OK, I`ll try to see it soon!

**Comment by m-onyshchuk** [comment]
For the rule to be checked, all the facts are needed. In your case, you need to add factTwo, factFour and factEight.
In version 1.1.17, I added the toExplainMore parameter to the constructor. If you enable it, then diagnostics of the rule operation will appear in the logs. Here is an example:

```
const {StugnaES} = require("stugna-es");
let es = new StugnaES({toExplainMore: true});
let factsIn = [
  {
    name: "factOne",
    value: 1,
    description: '',
  },
];
es.factsImport(factsIn);

let rulesIn = [
  {
    condition: "factOne = 1 OR factTwo = 1",
    factValue: "match",
    factName: "rule",
  }
];
es.ruleAdd(rulesIn[0]);

let events = es.eventsAll();
console.log (events);

```

**Comment by jamal-badawi-99** [comment]
So factTwo, factFour, and factEight need to exist in the knowledgebase no matter what their value is wether it's 1 or not for it to check?

**Comment by m-onyshchuk** [comment]
Yes, you are absolutely right!

**Comment by m-onyshchuk** [comment]
Hello, Jamal !
Some times ago new Stugna's version was deployed. It contains new rule's optional field - `missing`. This field are useful for OR condition calculation. Your example with new field will work fine. See below. 

```js
const {StugnaES} = require("stugna-es");
let es = new StugnaES({toExplainMore: true});
let factsIn = [
  { name: "factOne", value: 1 },
  { name: "factThree", value: 1 },
  { name: "factFive", value: 1 },
  { name: "factSix", value: 1 },
  { name: "factSeven", value: 1 },
];
es.factsImport(factsIn);

let rulesIn = [
  {
    condition: "(factOne = 1 OR factTwo = 1) AND factThree = 1 AND (factFour = 1 OR factFive = 1) AND factSix = 1 AND (factSeven = 1 OR factEight = 1)",
    missing: 0, // NEW RULE PARAM FOR MISSING FACTS 
    factValue: "match",
    factName: "rule",
  }
];
es.rulesImport(rulesIn);

let factsAll = es.factsAllAsMap();
console.log (factsAll);

/*
{
  factOne: 1,
  factThree: 1,
  factFive: 1,
  factSix: 1,
  factSeven: 1,
  rule: 'match'
}
*/
```
