### ISSUE TITLE
More example like Akinator

### ISSUE THREAD

**Issue by arturgspb** [m-onyshchuk/stugna#3]
Hi! Thanks for the library! 

Is there an example of work like Akinator (https://en.akinator.com/)? So that the system can generate a question and clarify the recommendation?

**Comment by m-onyshchuk** [comment]
Hello,
All examples are here:  https://github.com/m-onyshchuk/stugna/tree/main/examples
And they don't  contain variant like you wanted. To my mind any expert system can`t generate new things, buy  they can analyze existing facts, and Stugna is engine for expert systems and not for generative neural networks.

**Comment by arturgspb** [comment]
Sorry, by "generate a question" I meant an assumption about what fact needs to be clarified in order to quickly get the final answer. Those. in other words, calculate the probability - to clarify as little as possible and fill in more through factValue. I checked all the examples but really didn't find anything similar. Maybe not now, but I’m sure the library will be useful to me.

All the best!

**Comment by m-onyshchuk** [comment]
Unfortunately, it seems to me that I still do not understand your proposal clearly enough. Below I have sketched two examples to illustrate my point. Do I understand correctly that you need one of the methods:
```js
// Example 1
const {StugnaES} = require("stugna-es");
let es = new StugnaES();

es.rulesImport([
  {
    condition: "A > 1",
    factName: "Answer",
    factValue: "is known",
  },
  {
    condition: "B > 1",
    factName: "B1",
    factValue: 2,
  },
  {
    condition: "B1 > 1",
    factName: "Answer",
    factValue: "is known",
  }
]);

let wanted = es.factGetPredecessorsWanted("Answer");
console.log('wanted', wanted);
let unknown = es.factGetPredecessorsUnknown("Answer");
console.log ('unknown', unknown);

// wanted [ 'A', 'B1', 'B' ]
// unknown [ 'A', 'B' ]
```
1) to find the shortest path to answer (A vs B > B1)?


```js
// Example 2
const {StugnaES} = require("stugna-es");
let es = new StugnaES();

es.rulesImport([
  {
    condition: "A > 1",
    factName: "Answer",
    factValue: "by one fact",
  },
  {
    condition: "B > 1 AND C > 1 ",
    factName: "Answer",
    factValue: "by two facts",
  }
]);

let wanted = es.factGetPredecessorsWanted("Answer");
console.log('wanted', wanted);
let unknown = es.factGetPredecessorsUnknown("Answer");
console.log ('unknown', unknown);

// wanted [ 'A', 'B', 'C' ]
// unknown [ 'A', 'B', 'C' ]
```
2) to find the smallest set of facts for answer (A vs B & C)?


P.S. Would you be so kind as to write how you found out about the Stugna library?

**Comment by arturgspb** [comment]
I searched https://www.npmjs.com/search?q=expert%20systems =) 
Also I searched lib for python as variant.

Let me describe what I want to get. I think this will make everything much clearer.

I need to ask a certain number of questions to help make a diagnosis. For example, if a person has a leg pain, then you need to start asking questions where exactly and how, gradually narrowing the range of potential pathologies. Next, ask 20-30 clarifying questions to narrow down the range of possible treatment recommendations.

I'm still not 100% sure that this library is suitable, but I would like to understand its capabilities. Essentially I need something like a binary tree, but based on probabilities. Preferably with the possibility of errors when filling out the data (since people may choose incorrectly).Maybe here you can get the fact gradually, and by understanding which fact is not filled in, ask the following questions. Something like this.

Thank you in advance!

**Comment by m-onyshchuk** [comment]
Yes, you are right, it became much clearer.
I think that it will not be possible to use Stugna in your project, because you have interactivity -  user interaction. It seems to me that you do not need a binary tree, but a tool for working with a graph. If there are few nodes in the graph or you want to quickly sketch out a prototype, then it can be done in pure HTML. One question - one page, answer options - links to other pages with subsequent questions. If there are a lot of nodes, you can use Python and a graph database in which to store questions and probabilities of transition to other nodes. And to interact with the user, use one of the frameworks (Django, Flask, etc)
Good luck!

**Comment by arturgspb** [comment]
I didn’t expect HTML support from the library)) I’ll draw the forms and so on myself. I’m rather talking about the core of the system, which can choose what exactly needs to be clarified and calculate the probabilities of the final answers. In any case, thanks! I'll take a look and if something works out, I'll write to you. 

Have a nice day and thanks for your time!
